<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo (http://webpages.charter.net/edreamleo/front.html) -->
<?xml-stylesheet ekr_test?>
<leo_file xmlns:leo="http://www.leo-editor.org/2011/leo" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="georgesawyer.20110726113601.1427"><vh>@read-file-into-node C:/Documents and Settings/Mark/My Documents/develop/try-emacs/emacs-cheat-sheet.txt</vh></v>
<v t="georgesawyer.20110726113601.1430"><vh>@read-file-into-node C:/Documents and Settings/Mark/My Documents/develop/try-emacs/try-emacs.txt</vh></v>
<v t="georgesawyer.20110726113601.1429"><vh>@read-file-into-node C:/Documents and Settings/Mark/My Documents/develop/try-emacs/try2-emacs.txt</vh></v>
</vnodes>
<tnodes>
<t tx="georgesawyer.20110726113601.1427">@nocolor
http://stackoverflow.com/questions/269812/how-to-quickly-get-started-at-using-and-learning-emacs
http://stackoverflow.com/questions/270930/using-emacs-to-recursively-find-and-replace-in-text-files-not-already-open
http://www.emacswiki.org/emacs/Icicles
use c:\progra\emacs-23.1/
Per http://www.gnu.org/software/emacs/windows/Installing-Emacs.html:
Per 'Where do I put my init file?', section 3.5:
'.emacs' file is C:\Documents and Settings\Mark\Application Data\.emacs.d\init.el .
Per 'Troubleshooting init file problems', section 3.5.1:
To see an environment veriable (e.g., HOME), evaluate an expression in the *scratch* buffer using C-x C-e:
(getenv "HOME")
</t>
<t tx="georgesawyer.20110726113601.1429">@nocolor

 
 this 
 is
 some lines
 
 ft
</t>
<t tx="georgesawyer.20110726113601.1430">@nocolor
asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf
asdf asdf asdf asdf asdf asdf this is new asdf asdf asdf asdf asdf
asdf asdf asdf asdf asdf asdf asdf asdf asdf abcnew
</t>
</tnodes>
</leo_file>
